unique_ids:
  assets:
    standard-page.html: Z75GSAFSQH23SFODXM6PRXUFJWW7GBYI
    theme.css: I2FPNXRZTUWISJC44L6JNICLXMHT6OT4
  forms:
    Form1: VRBDBZGT2KR76AVRKCIMOS2TIENPNDHP
  modules: {}
  scripts: {}
  server_modules: {}
